# Generated by Django 3.2.4 on 2021-11-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='teak',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
