# Generated by Django 3.1 on 2022-06-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_teak'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogRe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('phone', models.PositiveIntegerField(unique=True)),
                ('mail', models.EmailField(max_length=30, unique=True)),
                ('pas1', models.CharField(max_length=15, unique=True)),
                ('pas2', models.CharField(max_length=15)),
            ],
        ),
    ]
