# Generated by Django 3.1 on 2022-06-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userlogre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='add_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='update_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
